trigger:
- main
 
pool:
  uipath
 
steps:

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Part02_Add Existing Part using Palette_tab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_02_Show Substitute for Selected BOM Items/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_04_Show BOM Item substitutes for selected Parts/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_05_Show all Substitute BOM Items for PL Item/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_06_Add Substitute and show it on PL/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'


 
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions01_Save As opertaion on source Variant/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
  
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions02_Select a Variant in Matrix table/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions03_Open a Variant from Matrix Table/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions04_and_05_Create New variant from MatrixTable and Delete from PL/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions06_Copy Paste operation from Source to Target Variant/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Edit Matrix table_01_02_03_CombinedOperations/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Filter01.1_Filter Variants in BOM Matrix/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'


- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Filter02_Filter Variants in BOM Matrix/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_MatCon01_Export BOM Matrix table/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'


- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_MatCon04_Reset Variant Matrix/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'



- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_MatCon05_Validate Overlapping BOM Variants/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL01_Create New Product Line Item/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL02_Verify Tabs for Product Line Item/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Module02_Add existing Module_OR_Product Line to the Product line/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL03_Verify UI Components of VM tab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL04_Verify command positioning on VM tab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL05_Position of Variant Matrix tab on UI/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL09_Position of Full screen button on UI/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Deleting Ouput folder'





