trigger:
- main

pool:
  uipath

stages:


- stage: VM_PL01_CreateNewProductLineItem
  jobs:
  - job: PackDeploy
    steps:
    - task: UiPathPack@4
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/VM_PL01_CreateNewProductLineItem/project.json'
        orchestratorConnection: 'Uipath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
    - task: UiPathDeploy@4
      inputs:
        orchestratorConnection: 'Uipath'
        packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
        folderName: 'Variant_Matrix_Automations'
    - script: |
       del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
      displayName: 'Delete output folder'

# Stage for VM_ColumnOpertaions01_SaveAsOpertaionOnSourceVariant
- stage: VM_ColumnOpertaions01_SaveAsOpertaionOnSourceVariant
  jobs:
  - job: PackDeploy
    steps:
    - task: UiPathPack@4
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions01_SaveAsOpertaionOnSourceVariant/project.json'
        orchestratorConnection: 'Uipath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
    - task: UiPathDeploy@4
      inputs:
        orchestratorConnection: 'Uipath'
        packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
        folderName: 'Variant_Matrix_Automations'
    - script: |
       del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
      displayName: 'Delete output folder'

# Stage for VM_ColumnOpertaions02_SelectVariantInMatrixtable
- stage: VM_ColumnOpertaions02_SelectVariantInMatrixtable
  jobs:
  - job: PackDeploy
    steps:
    - task: UiPathPack@4
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions02_SelectVariantInMatrixtable/project.json'
        orchestratorConnection: 'Uipath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
    - task: UiPathDeploy@4
      inputs:
        orchestratorConnection: 'Uipath'
        packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
        folderName: 'Variant_Matrix_Automations'
    - script: |
       del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
      displayName: 'Delete output folder'

# Stage for VM_ColumnOpertaions03_OpenVariantfromMatrixTable
- stage: VM_ColumnOpertaions03_OpenVariantfromMatrixTable
  jobs:
  - job: PackDeploy
    steps:
    - task: UiPathPack@4
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions03_OpenVariantfromMatrixTable/project.json'
        orchestratorConnection: 'Uipath'
        outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
    - task: UiPathDeploy@4
      inputs:
        orchestratorConnection: 'Uipath'
        packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
        folderName: 'Variant_Matrix_Automations'
    - script: |
       del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
      displayName: 'Delete output folder'





