trigger:
- main
 
pool:
  uipath
 
steps:

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'VM_ColumnOpertaions01_Save As opertaion on source Variant/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Variant_Matrix_Automations'





